export const GET_INGREDIENTS_OK = "GET_INGREDIENTS_OK";
export const GET_INGREDIENTS_ERR = "GET_INGREDIENTS_ERR";
export const INGREDIENT_DETAILS_ADD = "INGREDIENT_DETAILS_OPEN"
export const INGREDIENT_DETAILS_DELETE = "INGREDIENT_DETAILS_DELETE"